### ISSUE TITLE
How to make a pullrequest.

### ISSUE THREAD

**Issue by gvanbeck** [daeMOn63/bitclient#4]
It is not clear to me how one can make a pullrequest?

**Comment by daeMOn63** [comment]
You have to POST to `/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests` I guess (see https://docs.atlassian.com/bitbucket-server/rest/4.13.1/bitbucket-rest.html#idm46065330421600)
But it's not implemented by this client yet.
